org: ## Fyll i er egen organisation
service: backend

provider:
    name: aws
    runtime: nodejs20.x
    region: eu-north-1
    iam:
        role: ## Fyll i en egen roll
    httpApi:
        cors: true

functions:
    login:
        handler: functions/login/index.handler
        events:
            - httpApi:
                  path: /login
                  method: post
    getData:
        handler: functions/getData/index.handler
        events:
            - httpApi:
                  path: /data
                  method: get
